//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDMovies.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Gatuneks = new HashSet<Gatunek>();
        }
    
        public int ID_filmu { get; set; }
        public string Tytul { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime Data_premiery { get; set; }
        public string Ogr_wiekowe { get; set; }
        public int Czas_trwania { get; set; }
        public string Nosnik { get; set; }
        public int Ilosc { get; set; }
        public string Wycofany { get; set; }
        public byte[] Zdjecie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gatunek> Gatuneks { get; set; }
    }
}
